# Gradle JVM Memory & AndroidX Settings
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Users/negis/.jdks/jbr-17.0.14
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.configuration-cache=false
ksp.incremental=false


